# Generated by Django 2.1.7 on 2019-03-01 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='visitor_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('name_2', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('id_no', models.CharField(max_length=256)),
                ('id_type', models.CharField(max_length=256)),
                ('mob', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('veh', models.CharField(max_length=256)),
                ('purpose', models.CharField(max_length=256)),
                ('dest', models.CharField(max_length=256)),
                ('time_in', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status_in', models.BooleanField(default=True)),
                ('time_out', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('pic', models.CharField(max_length=100000)),
            ],
        ),
    ]
