# Generated by Django 2.1.4 on 2019-03-25 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor_detail',
            name='expected_out_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
